name: LavaVision
version: '${project.version}'
main: net.daechler.lavavision.LavaVision
api-version: 1.19
authors: [ Daechler ]
description: Lets you see through the lava.
commands:
  lavavision:
    description: Permission to use /lavavision
    usage: /lavavision
    permission: lavavision.use
